version: 2.1

orbs:
  slack: circleci/slack@4.4.2

jobs:
  init_aws:
    parameters:
      aws_access_key_id:
        description: AWS Access Key Id
        type: string

workflows:
  wd-web-platform:
    jobs:
      - init_aws:
